# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20171207_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='名称', max_length=100, verbose_name='名称')),
                ('brief', models.TextField(db_column='简介', max_length=500, verbose_name='简介')),
                ('category', models.CharField(default='', max_length=20, verbose_name='数据类别')),
                ('download', models.FileField(max_length=1000, upload_to='data/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '数据资源',
                'verbose_name': '数据资源',
            },
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': '图表', 'verbose_name_plural': '图表'},
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='click_num',
            new_name='click_nums',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='fav_num',
            new_name='fav_nums',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='访问地址'),
        ),
        migrations.AddField(
            model_name='chart',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
        migrations.AlterModelTable(
            name='chart',
            table='图表',
        ),
    ]
