# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 20:21
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_column='轮播图片', upload_to='chartsite/banner/', verbose_name='轮播图片')),
                ('index', models.IntegerField(db_column='轮播顺序', default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'db_table': '轮播图片',
                'verbose_name': '轮播图片',
                'verbose_name_plural': '轮播图片',
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_sn', models.CharField(db_column='图表编号', default='', max_length=50, verbose_name='图表编号')),
                ('name', models.CharField(db_column='图表名', max_length=100, verbose_name='图表名')),
                ('click_num', models.IntegerField(db_column='点击数', default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(db_column='收藏数', default=0, verbose_name='收藏数')),
                ('brief', models.TextField(db_column='简述', max_length=500, verbose_name='简述')),
                ('desc', DjangoUeditor.models.UEditorField(db_column='内容', default='', verbose_name='内容')),
                ('surface', models.ImageField(blank=True, db_column='封面图', null=True, upload_to='goods/images/', verbose_name='封面图')),
                ('is_new', models.BooleanField(db_column='是否新图', default=False, verbose_name='是否新图')),
                ('is_hot', models.BooleanField(db_column='是否热搜', default=False, verbose_name='是否热搜')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'db_table': '图表展示',
                'verbose_name': '图表展示',
                'verbose_name_plural': '图表展示',
            },
        ),
        migrations.CreateModel(
            name='ChartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '农业'), (2, '林业'), (3, '牧业'), (3, '牧业'), (4, '渔业'), (5, '农村'), (6, '产业'), (7, '农民'), (7, '其他')], help_text='图表类别', verbose_name='图表类别')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'db_table': '图表类别',
                'verbose_name': '图表类别',
                'verbose_name_plural': '图表类别',
            },
        ),
        migrations.CreateModel(
            name='ChartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, db_column='图片', null=True, upload_to='chart/images/', verbose_name='图片')),
                ('link', models.CharField(blank=True, db_column='链接', max_length=100, null=True, verbose_name='链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('chart', models.ForeignKey(db_column='图片名', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chart.Chart', verbose_name='图片名')),
            ],
            options={
                'db_table': '图表图片',
                'verbose_name': '图表图片',
                'verbose_name_plural': '图表图片',
            },
        ),
        migrations.CreateModel(
            name='HotSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='热搜')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'db_table': '热搜排行',
                'verbose_name': '热搜排行',
                'verbose_name_plural': '热搜排行',
            },
        ),
        migrations.CreateModel(
            name='YearBooks',
            fields=[
                ('id', models.IntegerField(verbose_name='同级顺序')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('category', models.CharField(max_length=60, verbose_name='父类')),
                ('page', models.CharField(max_length=20, verbose_name='页码')),
                ('identify', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='唯一编号')),
                ('year', models.CharField(max_length=4, verbose_name='唯一编号')),
            ],
            options={
                'db_table': '统计年鉴目录',
                'verbose_name': '统计年鉴目录',
                'verbose_name_plural': '统计年鉴目录',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='category',
            field=models.ForeignKey(db_column='图表类别', on_delete=django.db.models.deletion.CASCADE, to='chart.ChartCategory', verbose_name='图表类别'),
        ),
        migrations.AddField(
            model_name='banner',
            name='chart',
            field=models.ForeignKey(db_column='图片', on_delete=django.db.models.deletion.CASCADE, to='chart.Chart', verbose_name='图片'),
        ),
    ]
