# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearBooks',
        ),
    ]
