# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='surface',
            field=models.ImageField(blank=True, db_column='封面图', null=True, upload_to='chart/images/', verbose_name='封面图'),
        ),
    ]
