# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_delete_yearbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': '图表资源', 'verbose_name_plural': '图表资源'},
        ),
        migrations.AddField(
            model_name='chart',
            name='link',
            field=models.CharField(db_column='链接', default='img/2017092711174396.jpg', max_length=100, verbose_name='链接'),
        ),
        migrations.AlterModelTable(
            name='chart',
            table='图表资源',
        ),
    ]
