# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20171127_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(db_column='轮播图片', upload_to='chartsite/banner/', verbose_name='轮播图片'),
        ),
    ]
