# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20171127_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='yearbooks',
            fields=[
                ('id', models.IntegerField(verbose_name='同级顺序')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('category', models.CharField(max_length=60, verbose_name='父类')),
                ('page', models.CharField(max_length=10, verbose_name='页码')),
                ('identify', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='唯一编号')),
                ('year', models.CharField(max_length=4, verbose_name='唯一编号')),
            ],
            options={
                'verbose_name': '统计年鉴目录',
                'verbose_name_plural': '统计年鉴目录',
                'db_table': '统计年鉴目录',
            },
        ),
    ]
