# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171218_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(default='这个家伙很懒，什么也没有留下～～！', verbose_name='个人介绍'),
        ),
    ]
