# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_unit',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='职位'),
        ),
    ]
