# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, db_column='内容', null=True, verbose_name='内容')),
                ('resource', models.CharField(blank=True, db_column='来源', max_length=100, null=True, verbose_name='来源')),
                ('display', models.BooleanField(db_column='是否展示', default=False, verbose_name='是否展示')),
                ('is_hot', models.BooleanField(db_column='是否热点', default=False, verbose_name='是否热点')),
                ('add_time', models.DateTimeField(db_column='添加时间', default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '新闻动态',
                'verbose_name': '新闻动态',
                'db_table': '新闻动态',
            },
        ),
        migrations.CreateModel(
            name='RelatedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, db_column='顺序', null=True, verbose_name='顺序')),
                ('name', models.CharField(blank=True, db_column='名称', max_length=60, null=True, verbose_name='名称')),
                ('link', models.CharField(blank=True, db_column='链接', max_length=100, null=True, verbose_name='链接')),
                ('display', models.BooleanField(db_column='是否显示', default=False, verbose_name='是否显示')),
                ('add_time', models.DateTimeField(db_column='添加时间', default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '相关链接',
                'verbose_name': '相关链接',
                'db_table': '相关链接',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, db_column='内容', null=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(db_column='添加时间', default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '网站信息',
                'verbose_name': '网站信息',
                'db_table': '网站信息',
            },
        ),
    ]
