# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='名称', max_length=60, verbose_name='名称')),
                ('link', models.CharField(db_column='链接', max_length=100, verbose_name='链接')),
            ],
            options={
                'db_table': '相关链接',
                'verbose_name_plural': '相关链接',
                'verbose_name': '相关链接',
            },
        ),
    ]
