# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, db_column='内容', null=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(db_column='添加时间', default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '网站信息',
                'db_table': '网站信息',
                'verbose_name_plural': '网站信息',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='resource',
            field=models.CharField(blank=True, db_column='来源', max_length=100, null=True, verbose_name='来源'),
        ),
    ]
