# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 21:18
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=DjangoUeditor.models.UEditorField(db_column='内容', default='', verbose_name='内容'),
        ),
    ]
