# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 17:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Chart', verbose_name='图表')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '图表评论',
                'db_table': '图表评论',
                'verbose_name_plural': '图表评论',
            },
        ),
        migrations.CreateModel(
            name='DataShare',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='标题', max_length=100, verbose_name='标题')),
                ('desc', models.TextField(blank=True, db_column='文件描述', null=True, verbose_name='文件描述')),
                ('type', models.IntegerField(choices=[(1, 'txt'), (2, 'pdf'), (3, 'caj'), (4, 'csv'), (5, 'json'), (6, 'excel'), (7, '图片')], db_column='文件类型', verbose_name='文件类型')),
                ('click_nums', models.IntegerField(db_column='点击数', default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(db_column='收藏数', default=0, verbose_name='收藏数')),
                ('down_nums', models.IntegerField(db_column='下载数', default=0, verbose_name='下载数')),
                ('file', models.FileField(db_column='上传文件', upload_to='datashare/file', verbose_name='上传文件')),
                ('resource', models.CharField(blank=True, db_column='数据来源', max_length=50, null=True, verbose_name='数据来源')),
                ('size', models.CharField(blank=True, db_column='文件大小', max_length=50, null=True, verbose_name='文件大小')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, db_column='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '数据共享',
                'db_table': '数据共享',
                'verbose_name_plural': '数据共享',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column='主题', default='', max_length=100, verbose_name='主题')),
                ('message_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '建议')], db_column='留言类型', default=1, verbose_name='留言类型')),
                ('message', models.TextField(db_column='留言内容', default='', help_text='留言内容', verbose_name='留言内容')),
                ('file', models.FileField(db_column='上传的文件', help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, db_column='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户留言',
                'db_table': '用户留言',
                'verbose_name_plural': '用户留言',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('chart', models.ForeignKey(blank=True, db_column='图片', null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Chart', verbose_name='图片')),
                ('user', models.ForeignKey(blank=True, db_column='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'db_table': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='接收用户')),
                ('message', models.TextField(default='', verbose_name='消息内容')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户消息',
                'db_table': '用户消息',
                'verbose_name_plural': '用户消息',
            },
        ),
    ]
