# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashare',
            name='click_nums',
            field=models.IntegerField(db_column='点击数', default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='datashare',
            name='down_nums',
            field=models.IntegerField(db_column='下载数', default=0, verbose_name='下载数'),
        ),
        migrations.AddField(
            model_name='datashare',
            name='fav_nums',
            field=models.IntegerField(db_column='收藏数', default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='datashare',
            name='resource',
            field=models.CharField(blank=True, db_column='数据来源', max_length=50, null=True, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='datashare',
            name='size',
            field=models.CharField(blank=True, db_column='文件大小', max_length=50, null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='datashare',
            name='desc',
            field=models.TextField(blank=True, db_column='文件描述', null=True, verbose_name='文件描述'),
        ),
    ]
