# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '建议')], db_column='留言类型', default=1, verbose_name='留言类型'),
        ),
    ]
