# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20171207_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataShare',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='标题', max_length=100, verbose_name='标题')),
                ('desc', models.TextField(db_column='文件描述', verbose_name='文件描述')),
                ('type', models.BooleanField(choices=[(1, 'txt'), (2, 'pdf'), (3, 'caj'), (4, 'csv'), (5, 'json'), (6, 'excel'), (7, '图片')], db_column='文件类型', max_length=20, verbose_name='文件类型')),
                ('file', models.FileField(db_column='上传文件', upload_to='datashare/file', verbose_name='上传文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(db_column='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': '用户留言',
                'verbose_name_plural': '用户留言',
                'verbose_name': '用户留言',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(db_column='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(db_column='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
