# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20171127_1137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='用户留言',
        ),
        migrations.AlterModelTable(
            name='userfav',
            table='用户收藏',
        ),
    ]
