# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20171207_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
