# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180202_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datashare',
            name='type',
            field=models.IntegerField(choices=[(1, 'txt'), (2, 'pdf'), (3, 'caj'), (4, 'csv'), (5, 'json'), (6, 'excel'), (7, '图片')], db_column='文件类型', verbose_name='文件类型'),
        ),
    ]
