# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20171127_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], db_column='留言类型', default=1, verbose_name='留言类型'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='chart',
            field=models.ForeignKey(db_column='图片', on_delete=django.db.models.deletion.CASCADE, to='chart.Chart', verbose_name='图片'),
        ),
    ]
