# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_auto_20171207_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column='主题', default='', max_length=100, verbose_name='主题')),
                ('message_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '建议')], db_column='留言类型', default=1, verbose_name='留言类型')),
                ('message', models.TextField(db_column='留言内容', default='', help_text='留言内容', verbose_name='留言内容')),
                ('file', models.FileField(db_column='上传的文件', help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(db_column='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
                'db_table': '用户留言',
            },
        ),
    ]
