# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datashare',
            options={'verbose_name': '数据共享', 'verbose_name_plural': '数据共享'},
        ),
        migrations.AlterModelTable(
            name='datashare',
            table='数据共享',
        ),
    ]
