# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgnyyhswdbtp',
            name='link',
            field=models.CharField(blank=True, db_column='链接', max_length=100, null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='zgzynywhyctp',
            name='path',
            field=models.CharField(blank=True, db_column='路径', max_length=100, null=True, verbose_name='路径'),
        ),
    ]
