# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20171206_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgnyyhswdbtp',
            name='link',
            field=models.ImageField(db_column='链接', default=1, upload_to='agridata/images', verbose_name='链接'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zgzynywhyctp',
            name='path',
            field=models.ImageField(db_column='路径', default=1, upload_to='agridata/culture', verbose_name='路径'),
            preserve_default=False,
        ),
    ]
