# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_relatedsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedsite',
            name='add_time',
            field=models.DateTimeField(db_column='添加时间', default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='relatedsite',
            name='display',
            field=models.BooleanField(db_column='是否显示', default=False, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='relatedsite',
            name='index',
            field=models.IntegerField(blank=True, db_column='顺序', max_length=4, null=True, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='relatedsite',
            name='link',
            field=models.CharField(blank=True, db_column='链接', max_length=100, null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='relatedsite',
            name='name',
            field=models.CharField(blank=True, db_column='名称', max_length=60, null=True, verbose_name='名称'),
        ),
    ]
