# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20171207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedsite',
            name='index',
            field=models.IntegerField(blank=True, db_column='顺序', null=True, verbose_name='顺序'),
        ),
    ]
