# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GjnykyhzxmDb',
        ),
        migrations.DeleteModel(
            name='GnnykyhzxmDb',
        ),
        migrations.DeleteModel(
            name='NybzhczgfDb',
        ),
        migrations.RemoveField(
            model_name='nygjtpdb',
            name='reportid',
        ),
        migrations.DeleteModel(
            name='NyhjkjcgDb',
        ),
        migrations.DeleteModel(
            name='NykjjgDb',
        ),
        migrations.DeleteModel(
            name='NykjrcDb',
        ),
        migrations.DeleteModel(
            name='NykjzcfgDb',
        ),
        migrations.DeleteModel(
            name='WwkjwxDb',
        ),
        migrations.DeleteModel(
            name='XqfzffDb',
        ),
        migrations.DeleteModel(
            name='YjnyDb',
        ),
        migrations.DeleteModel(
            name='NygjDb',
        ),
        migrations.DeleteModel(
            name='NygjtpDb',
        ),
    ]
