# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nygjdb',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True),
        ),
    ]
