# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='标题', max_length=60, null=True, verbose_name='标题')),
            ],
            options={
                'db_table': 'CsvHtml',
                'verbose_name_plural': 'CsvHtml',
                'verbose_name': 'CsvHtml',
            },
        ),
    ]
