# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwyjzwzzzydb',
            name='comment',
            field=models.CharField(blank=True, db_column='备注', max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='gwyjzwzzzydb',
            name='import_time',
            field=models.CharField(blank=True, db_column='引入时间', max_length=100, null=True, verbose_name='引入时间'),
        ),
    ]
