# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgxzqhdb',
            name='adcode',
            field=models.CharField(db_column='地址编码', max_length=6, primary_key=True, verbose_name='地址编码'),
        ),
    ]
