# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20171126_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xzqhlist',
            old_name='county',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='xzqhlist',
            old_name='countycode',
            new_name='districtcode',
        ),
        migrations.AddField(
            model_name='ncpjghqzdcode',
            name='bound',
            field=models.CharField(blank=True, db_column='面源坐标', max_length=60, null=True, verbose_name='面源坐标'),
        ),
        migrations.AddField(
            model_name='ncpjghqzdcode',
            name='city',
            field=models.CharField(blank=True, db_column='城市', max_length=30, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='ncpjghqzdcode',
            name='district',
            field=models.CharField(blank=True, db_column='区县', max_length=20, null=True, verbose_name='区县'),
        ),
        migrations.AddField(
            model_name='ncpjghqzdcode',
            name='formatted_address',
            field=models.CharField(blank=True, db_column='绝对地址', max_length=60, null=True, verbose_name='绝对地址'),
        ),
        migrations.AddField(
            model_name='ncpjghqzdcode',
            name='location',
            field=models.CharField(blank=True, db_column='位置', max_length=60, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='ncpjghqzdcode',
            name='province',
            field=models.CharField(blank=True, db_column='省份', max_length=30, null=True, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='xzqhlist',
            name='bound',
            field=models.CharField(blank=True, db_column='面源坐标', max_length=60, null=True, verbose_name='面源坐标'),
        ),
        migrations.AddField(
            model_name='xzqhlist',
            name='formatted_address',
            field=models.CharField(blank=True, db_column='绝对地址', max_length=60, null=True, verbose_name='绝对地址'),
        ),
    ]
