# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_csvhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvhtml',
            name='file',
            field=models.FilePathField(blank=True, db_column='下载链接', max_length=60, null=True, verbose_name='下载链接'),
        ),
    ]
