# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20171124_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgxzqhdb',
            name='center',
            field=models.CharField(db_column='中心坐标', max_length=30, primary_key=True, serialize=False, verbose_name='中心坐标'),
        ),
    ]
