# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': '数据资源列表', 'verbose_name_plural': '数据资源列表'},
        ),
        migrations.AlterModelTable(
            name='resource',
            table='数据资源列表',
        ),
    ]
