# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20171228_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.IntegerField(choices=[(1, '农业'), (2, '林业'), (3, '牧业'), (4, '渔业'), (5, '农村'), (6, '农民'), (7, '植物'), (7, '动物')], db_column='类别', max_length=4, verbose_name='类别'),
        ),
    ]
