# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20171124_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgxzqhdb',
            name='center',
            field=models.CharField(db_column='中心坐标', max_length=30, primary_key=True, verbose_name='中心坐标'),
        ),
        migrations.AlterIndexTogether(
            name='zgxzqhdb',
            index_together=set([('name', 'adcode', 'center')]),
        ),
    ]
