# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20180203_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, db_column='顺序', null=True, verbose_name='顺序')),
                ('content', models.CharField(blank=True, db_column='目录', max_length=30, null=True, verbose_name='目录')),
                ('fieldtype', models.CharField(blank=True, db_column='字段类型', max_length=20, null=True, verbose_name='字段类型')),
                ('fieldlength', models.CharField(blank=True, db_column='字段长度', max_length=10, null=True, verbose_name='字段长度')),
                ('display', models.IntegerField(blank=True, db_column='是否显示', default=0, null=True, verbose_name='是否显示')),
                ('english', models.CharField(blank=True, db_column='字段', max_length=20, null=True, verbose_name='字段')),
                ('title', models.ForeignKey(blank=True, db_column='数据集名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.AgriTechDes', verbose_name='数据集名称')),
            ],
            options={
                'verbose_name': '字段数据目录',
                'db_table': '字段数据目录',
                'verbose_name_plural': '字段数据目录',
            },
        ),
        migrations.AlterField(
            model_name='nygjdb',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True),
        ),
    ]
