# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_gjnykyhzxmdb_gnnykyhzxmdb_nybzhczgfdb_nygjdb_nygjtpdb_nyhjkjcgdb_nykjjgdb_nykjrcdb_nykjzcfgdb_wwkjwx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytxdb',
            name='code',
            field=models.CharField(blank=True, db_column='索引', default='', max_length=40, null=True, verbose_name='索引'),
        ),
        migrations.AlterField(
            model_name='mytxdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
