# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20171124_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zgxzqhdb',
            unique_together=set([]),
        ),
    ]
