# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20180420_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvhtml',
            name='file',
            field=models.FileField(blank=True, db_column='下载', max_length=60, null=True, upload_to='text/', verbose_name='下载'),
        ),
    ]
