# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20180203_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nygjdb',
            name='reportid',
            field=models.CharField(db_column='记录号', max_length=64, primary_key=True, verbose_name='记录号'),
        ),
    ]
