# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20180203_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcontent',
            name='title',
            field=models.CharField(blank=True, db_column='数据集名称', max_length=30, null=True, verbose_name='数据集名称'),
        ),
    ]
