# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20171124_1004'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='zgxzqhdb',
            index_together=set([]),
        ),
        migrations.AddIndex(
            model_name='zgxzqhdb',
            index=models.Index(fields=['name', 'adcode', 'center'], name='index'),
        ),
    ]
