# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20180420_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvhtml',
            old_name='title',
            new_name='slug',
        ),
    ]
