# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20171228_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='ResourceList',
        ),
    ]
