# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20171228_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwwzfbdb',
            name='path',
            field=models.ImageField(blank=True, db_column='路径', max_length=80, null=True, upload_to='', verbose_name='路径'),
        ),
    ]
