# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20171124_1011'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zgxzqhdb',
            name='index',
        ),
        migrations.AlterUniqueTogether(
            name='zgxzqhdb',
            unique_together=set([('name', 'adcode', 'center')]),
        ),
    ]
