# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20180128_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelist',
            name='image',
            field=models.ImageField(blank=True, db_column='数据封面', null=True, upload_to='resource/images', verbose_name='数据封面'),
        ),
        migrations.AlterField(
            model_name='resourcelist',
            name='title',
            field=models.CharField(db_column='标题', default=1, max_length=30, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
