# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20180420_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvHtmls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, db_column='标题', max_length=60, null=True, verbose_name='标题')),
                ('file', models.FileField(blank=True, db_column='下载', max_length=60, null=True, upload_to='text/', verbose_name='下载')),
                ('category', models.CharField(blank=True, db_column='类别', max_length=60, null=True, verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '下载文件',
                'verbose_name': '下载文件',
                'db_table': '下载文件',
            },
        ),
        migrations.DeleteModel(
            name='CsvHtml',
        ),
    ]
