# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20180203_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlyhzwdb',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zgnttdzzdb',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
