# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_auto_20180102_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdycpzjqpxdb',
            old_name='totalcode',
            new_name='total_id',
        ),
        migrations.AlterUniqueTogether(
            name='sdycpzjqpxdb',
            unique_together=set([('total_id', 'name')]),
        ),
    ]
