# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_gjnydbdes_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgtsncp',
            name='city',
            field=models.CharField(blank=True, db_column='市级', max_length=60, null=True, verbose_name='市级'),
        ),
        migrations.AddField(
            model_name='zgtsncp',
            name='district',
            field=models.CharField(blank=True, db_column='区县', max_length=60, null=True, verbose_name='区县'),
        ),
        migrations.AddField(
            model_name='zgtsncp',
            name='province',
            field=models.CharField(blank=True, db_column='省份', max_length=60, null=True, verbose_name='省份'),
        ),
    ]
