# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_auto_20171124_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgxzqhdb',
            options={'managed': False, 'verbose_name': '中国行政区划数据库', 'verbose_name_plural': '中国行政区划数据库'},
        ),
    ]
