# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_auto_20180131_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearbooks',
            name='id',
        ),
        migrations.AlterField(
            model_name='yearbooks',
            name='identify',
            field=models.CharField(db_column='唯一编号', max_length=20, primary_key=True, serialize=False, verbose_name='唯一编号'),
        ),
    ]
