# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_zwyczytxpjjddblist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwyczytxpjjddblist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
