# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_auto_20171124_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgjjzwbdbhdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
    ]
