# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0010_auto_20180131_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbooks',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', null=True, verbose_name='id'),
        ),
    ]
