# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_gjnykyhzxmdblist_gnnykyhzxmdblist_nyhjkjcgdblist_nykjjgdblist_nykjrcdblist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gjnykyhzxmdblist',
            name='category',
            field=models.CharField(db_column='专业分类', max_length=256, verbose_name='专业分类'),
        ),
        migrations.AlterField(
            model_name='gjnykyhzxmdblist',
            name='title',
            field=models.CharField(db_column='项目名称', max_length=256, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='gjnykyhzxmdblist',
            name='unit',
            field=models.CharField(db_column='承担机构', max_length=256, verbose_name='承担机构'),
        ),
        migrations.AlterField(
            model_name='gnnykyhzxmdblist',
            name='title',
            field=models.CharField(db_column='项目名称', max_length=256, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='gnnykyhzxmdblist',
            name='unit',
            field=models.CharField(db_column='承担单位', max_length=256, verbose_name='承担单位'),
        ),
        migrations.AlterField(
            model_name='nyhjkjcgdblist',
            name='email',
            field=models.CharField(db_column='联系人email', max_length=256, verbose_name='联系人email'),
        ),
        migrations.AlterField(
            model_name='nyhjkjcgdblist',
            name='title',
            field=models.CharField(db_column='成果名称', max_length=256, verbose_name='成果名称'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='address',
            field=models.CharField(db_column='通讯地址', max_length=256, verbose_name='通讯地址'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='email',
            field=models.CharField(db_column='电子邮箱', max_length=256, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='gfmc',
            field=models.CharField(db_column='规范名称', max_length=256, verbose_name='规范名称'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='net',
            field=models.CharField(db_column='网址', max_length=256, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='phone',
            field=models.CharField(db_column='联系电话', max_length=256, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='sjdw',
            field=models.CharField(db_column='上级单位', max_length=256, verbose_name='上级单位'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='szdq',
            field=models.CharField(db_column='所在地区', max_length=256, verbose_name='所在地区'),
        ),
        migrations.AlterField(
            model_name='nykjjgdblist',
            name='ywmc',
            field=models.CharField(db_column='英文名称', max_length=256, verbose_name='英文名称'),
        ),
        migrations.AlterField(
            model_name='nykjrcdblist',
            name='direction',
            field=models.CharField(db_column='研究方向', max_length=256, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='nykjrcdblist',
            name='field',
            field=models.CharField(db_column='专业领域', max_length=256, verbose_name='专业领域'),
        ),
        migrations.AlterField(
            model_name='nykjrcdblist',
            name='unit',
            field=models.CharField(db_column='工作单位', max_length=256, verbose_name='工作单位'),
        ),
        migrations.AlterField(
            model_name='nykjrcdblist',
            name='unitaddress',
            field=models.CharField(db_column='单位地址', max_length=256, verbose_name='单位地址'),
        ),
        migrations.AlterField(
            model_name='xiaomai',
            name='layudi',
            field=models.CharField(blank=True, db_column='来源地', max_length=256, null=True, verbose_name='来源地'),
        ),
    ]
