# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_auto_20171124_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgjjzwbdbhdb',
            name='by_xuename',
            field=models.TextField(blank=True, db_column='病原拉丁学名', null=True, verbose_name='病原拉丁学名'),
        ),
        migrations.AddField(
            model_name='zgjjzwbdbhdb',
            name='by_zhname',
            field=models.TextField(blank=True, db_column='病原中文名', max_length=60, null=True, verbose_name='病原中文名'),
        ),
    ]
