# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_delete_zgjjzwbdbhdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgjjzwbdbhDb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hazard_buwei', models.TextField(blank=True, db_column='主要危害部位', null=True, verbose_name='主要危害部位')),
                ('distribution', models.TextField(blank=True, db_column='地理分布', null=True, verbose_name='地理分布')),
                ('symptom', models.TextField(blank=True, db_column='为害症状', null=True, verbose_name='为害症状')),
                ('disease_type', models.CharField(blank=True, db_column='病害类型', max_length=30, null=True, verbose_name='病害类型')),
                ('zhname', models.CharField(blank=True, db_column='中文名', max_length=60, null=True, verbose_name='中文名')),
                ('by_zhname', models.TextField(blank=True, db_column='病原中文名', max_length=60, null=True, verbose_name='病原中文名')),
                ('by_xuename', models.TextField(blank=True, db_column='病原拉丁学名', null=True, verbose_name='病原拉丁学名')),
                ('major_hazard', models.TextField(blank=True, db_column='主要危害作物', null=True, verbose_name='主要危害作物')),
                ('alias', models.CharField(blank=True, db_column='别名', max_length=30, null=True, verbose_name='别名')),
                ('byfldw', models.CharField(blank=True, db_column='病原分类地位', max_length=30, null=True, verbose_name='病原分类地位')),
                ('byxttz', models.TextField(blank=True, db_column='病原形态特征', null=True, verbose_name='病原形态特征')),
                ('related_articles', models.TextField(blank=True, db_column='相关文献', null=True, verbose_name='相关文献')),
                ('control_way', models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法')),
                ('english', models.CharField(blank=True, db_column='英文名', max_length=60, null=True, verbose_name='英文名')),
                ('report_id', models.CharField(blank=True, db_column='记录号', max_length=10, null=True, verbose_name='记录号')),
                ('pathway_fbtj', models.TextField(blank=True, db_column='传播途径和发病条件', null=True, verbose_name='传播途径和发病条件')),
            ],
            options={
                'verbose_name': '中国经济作物病毒病害数据库',
                'verbose_name_plural': '中国经济作物病毒病害数据库',
                'db_table': '中国经济作物病毒病害数据库',
            },
        ),
    ]
