# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_auto_20180201_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbooks',
            name='url',
            field=models.FilePathField(blank=True, db_column='下载链接', null=True, verbose_name='下载链接'),
        ),
    ]
