# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_auto_20180109_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='nykjjgdblist',
            name='unitid',
            field=models.CharField(db_column='机构编号', default=1, max_length=64, verbose_name='机构编号'),
            preserve_default=False,
        ),
    ]
