# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0014_nykjjgdblist_unitid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GjnykyhzxmDbList',
            new_name='GjnykyhzxmDb',
        ),
        migrations.RenameModel(
            old_name='GnnykyhzxmDbList',
            new_name='GnnykyhzxmDb',
        ),
        migrations.RenameModel(
            old_name='NyhjkjcgDbList',
            new_name='NyhjkjcgDb',
        ),
        migrations.RenameModel(
            old_name='NykjjgDbList',
            new_name='NykjjgDb',
        ),
        migrations.RenameModel(
            old_name='NykjrcDbList',
            new_name='NykjrcDb',
        ),
    ]
