# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0015_auto_20171124_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgjjzwbdbhdb',
            name='by_xuename',
            field=models.TextField(blank=True, db_column='病原拉丁学名', null=True, verbose_name='病原拉丁学名'),
        ),
    ]
