# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0015_auto_20180109_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZwkjwxDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='题名', max_length=256, verbose_name='题名')),
                ('author', models.CharField(db_column='作者', max_length=512, verbose_name='作者')),
                ('unit', models.CharField(db_column='作者单位', max_length=512, verbose_name='作者单位')),
                ('qkname', models.CharField(db_column='期刊名称', max_length=128, verbose_name='期刊名称')),
                ('year', models.CharField(db_column='年份', max_length=16, verbose_name='年份')),
                ('juan', models.CharField(db_column='卷', max_length=16, verbose_name='卷')),
                ('qi', models.CharField(db_column='期', max_length=16, verbose_name='期')),
                ('page', models.CharField(db_column='页码', max_length=16, verbose_name='页码')),
                ('num', models.CharField(db_column='页数', max_length=16, verbose_name='页数')),
                ('keywords', models.CharField(db_column='关键词', max_length=512, verbose_name='关键词')),
                ('gntykh', models.CharField(db_column='国内统一刊号', max_length=32, verbose_name='国内统一刊号')),
                ('issn', models.CharField(db_column='ISSN', max_length=32, verbose_name='ISSN')),
                ('zwflh', models.CharField(db_column='中图分类号', max_length=32, verbose_name='中图分类号')),
                ('abstract', models.TextField(db_column='摘要', verbose_name='摘要')),
                ('ywname', models.CharField(db_column='英文题名', max_length=512, verbose_name='英文题名')),
                ('ywauthor', models.CharField(db_column='英文作者', max_length=1024, verbose_name='英文作者')),
                ('ywgjc', models.CharField(db_column='英文关键词', max_length=1024, verbose_name='英文关键词')),
                ('ywzy', models.TextField(db_column='英文摘要', verbose_name='英文摘要')),
                ('qkywname', models.CharField(db_column='期刊英文名称', max_length=512, verbose_name='期刊英文名称')),
                ('xmjjname', models.CharField(db_column='项目基金名称', max_length=512, verbose_name='项目基金名称')),
            ],
            options={
                'verbose_name_plural': '中文农业科技文摘数据库',
                'verbose_name': '中文农业科技文摘数据库',
                'db_table': '中文农业科技文摘数据库',
            },
        ),
    ]
