# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0016_zwkjwxdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='YjnyDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.CharField(db_column='记录号', max_length=32, verbose_name='记录号')),
                ('title', models.CharField(db_column='题名', max_length=256, verbose_name='题名')),
                ('author', models.CharField(db_column='作者', max_length=64, verbose_name='作者')),
                ('keywords', models.CharField(db_column='关键词', max_length=256, verbose_name='关键词')),
                ('category', models.CharField(db_column='分类', max_length=64, verbose_name='分类')),
                ('infotype', models.CharField(db_column='信息类型', max_length=16, verbose_name='信息类型')),
                ('resource', models.CharField(db_column='信息来源', max_length=128, verbose_name='信息来源')),
                ('datetimes', models.CharField(db_column='出版日期', max_length=32, verbose_name='出版日期')),
                ('gslb', models.CharField(db_column='归属类别', max_length=64, verbose_name='归属类别')),
                ('zwflh', models.CharField(db_column='中图分类号', max_length=64, verbose_name='中图分类号')),
                ('szzdw', models.CharField(db_column='首作者单位', max_length=128, verbose_name='首作者单位')),
                ('content', models.TextField(db_column='正文', verbose_name='正文')),
            ],
            options={
                'verbose_name_plural': '有机农业数据库',
                'verbose_name': '有机农业数据库',
                'db_table': '有机农业数据库',
            },
        ),
    ]
