# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_auto_20180201_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearBooksCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(db_column='编号', max_length=20, verbose_name='编号')),
                ('chinese', models.CharField(db_column='年鉴中文名', max_length=40, verbose_name='年鉴中文名')),
                ('english', models.CharField(db_column='年鉴英文名', max_length=60, verbose_name='年鉴英文名')),
                ('year', models.CharField(db_column='年鉴年份', max_length=4, verbose_name='年鉴年份')),
                ('author', models.CharField(db_column='责任说明', max_length=20, verbose_name='责任说明')),
                ('unit', models.CharField(db_column='主编单位', max_length=60, verbose_name='主编单位')),
                ('pubtime', models.CharField(db_column='出版日期', max_length=20, verbose_name='出版日期')),
                ('page', models.CharField(db_column='页数', max_length=20, verbose_name='页数')),
                ('money', models.CharField(db_column='人民币定价', max_length=20, verbose_name='人民币定价')),
                ('desc', models.TextField(db_column='内容简介', verbose_name='内容简介')),
                ('image', models.ImageField(db_column='封面', upload_to='yearbooks/images/', verbose_name='封面')),
            ],
            options={
                'verbose_name_plural': '农业统计年鉴概述',
                'verbose_name': '农业统计年鉴概述',
                'db_table': '农业统计年鉴概述',
            },
        ),
    ]
