# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_auto_20171124_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zglszwbdbhdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
        migrations.AlterField(
            model_name='zglszwxjbhdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
        migrations.AlterField(
            model_name='zglszwzjbhdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
        migrations.AlterField(
            model_name='zgmhhcdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
        migrations.AlterField(
            model_name='zgwlrqkcdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
        migrations.AlterField(
            model_name='zgwlrqzwdb',
            name='control_way',
            field=models.TextField(blank=True, db_column='防治方法', null=True, verbose_name='防治方法'),
        ),
    ]
