# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_yjnydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='NygjDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.CharField(db_column='记录号', max_length=64, verbose_name='记录号')),
                ('category', models.CharField(db_column='分类', max_length=64, verbose_name='分类')),
                ('title', models.CharField(db_column='标题书名', max_length=128, verbose_name='标题书名')),
                ('author', models.CharField(db_column='作者', max_length=64, verbose_name='作者')),
                ('infotype', models.CharField(db_column='信息类型', max_length=64, verbose_name='信息类型')),
                ('resource', models.CharField(db_column='信息来源', max_length=64, verbose_name='信息来源')),
                ('datetimes', models.CharField(db_column='出版日期', max_length=32, verbose_name='出版日期')),
                ('publish', models.CharField(db_column='出版者', max_length=128, verbose_name='出版者')),
                ('cbd', models.CharField(db_column='出版地', max_length=64, verbose_name='出版地')),
                ('ztxt', models.CharField(db_column='载体形态', max_length=64, verbose_name='载体形态')),
                ('dlh', models.CharField(db_column='登录号', max_length=64, verbose_name='登录号')),
                ('keywords', models.CharField(db_column='关键词', max_length=128, verbose_name='关键词')),
                ('content', models.TextField(db_column='正文文摘', verbose_name='正文文摘')),
                ('fujian', models.CharField(db_column='附件', max_length=128, verbose_name='附件')),
            ],
            options={
                'verbose_name': '农业古籍数据库',
                'db_table': '农业古籍数据库',
                'verbose_name_plural': '农业古籍数据库',
            },
        ),
    ]
