# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_auto_20171124_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zglszwxjbhdb',
            name='by_zhname',
            field=models.CharField(blank=True, db_column='病原中文名', max_length=60, null=True, verbose_name='病原中文名'),
        ),
    ]
