# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_nygjdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='NybzhczgfDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bzid', models.CharField(db_column='标准编号', max_length=32, verbose_name='标准编号')),
                ('bzname', models.CharField(db_column='标准名称', max_length=128, verbose_name='标准名称')),
                ('fbrq', models.CharField(db_column='发布日期', max_length=10, verbose_name='发布日期')),
                ('ssrq', models.CharField(db_column='实施日期', max_length=10, verbose_name='实施日期')),
                ('bzlx', models.CharField(db_column='标准类型', max_length=32, verbose_name='标准类型')),
                ('fbdw', models.CharField(db_column='发布单位', max_length=128, verbose_name='发布单位')),
                ('qcdw', models.CharField(db_column='起草单位', max_length=128, verbose_name='起草单位')),
                ('qcr', models.CharField(db_column='起草人', max_length=128, verbose_name='起草人')),
                ('bzgs', models.TextField(db_column='标准概述（300字以内）', verbose_name='标准概述（300字以内）')),
                ('content', models.TextField(db_column='全文', verbose_name='全文')),
            ],
            options={
                'verbose_name': '农业标准和操作规范数据库',
                'verbose_name_plural': '农业标准和操作规范数据库',
                'db_table': '农业标准和操作规范数据库',
            },
        ),
    ]
