# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0019_auto_20180201_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookscover',
            name='index',
            field=models.CharField(db_column='编号', max_length=20, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='yearbookscover',
            name='year',
            field=models.CharField(db_column='年鉴年份', max_length=4, primary_key=True, serialize=False, verbose_name='年鉴年份'),
        ),
    ]
