# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0019_nybzhczgfdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nygjdb',
            name='fujian',
            field=models.CharField(db_column='附件', max_length=256, verbose_name='附件'),
        ),
    ]
