# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0020_auto_20180110_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytxdb',
            name='brands',
            field=models.CharField(blank=True, db_column='作物品种', max_length=128, null=True, verbose_name='作物品种'),
        ),
        migrations.AlterField(
            model_name='mytxdb',
            name='brands_category',
            field=models.CharField(blank=True, db_column='品种类别', max_length=128, null=True, verbose_name='品种类别'),
        ),
        migrations.AlterField(
            model_name='mytxdb',
            name='category',
            field=models.CharField(blank=True, db_column='作物种类', max_length=128, null=True, verbose_name='作物种类'),
        ),
        migrations.AlterField(
            model_name='mytxdb',
            name='name',
            field=models.CharField(blank=True, db_column='品种名称', max_length=128, null=True, verbose_name='品种名称'),
        ),
        migrations.AlterField(
            model_name='mytxdb',
            name='raiser',
            field=models.CharField(blank=True, db_column='培育者', max_length=256, null=True, verbose_name='培育者'),
        ),
    ]
