# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0021_auto_20180111_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytxdb',
            name='examine',
            field=models.TextField(blank=True, db_column='审定情况', null=True, verbose_name='审定情况'),
        ),
    ]
