# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0021_auto_20171124_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgnttdzzdb',
            name='xuename',
            field=models.CharField(blank=True, db_column='拉丁学名', max_length=60, null=True, verbose_name='拉丁学名'),
        ),
    ]
