# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0021_auto_20180201_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearBooksContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_column='顺序', verbose_name='顺序')),
                ('content', models.CharField(db_column='目录', max_length=40, verbose_name='目录')),
                ('year', models.ForeignKey(db_column='年鉴年份', on_delete=django.db.models.deletion.CASCADE, to='resource.YearBooksDes', verbose_name='年鉴年份')),
            ],
            options={
                'db_table': '农业统计年鉴目录',
                'verbose_name': '农业统计年鉴目录',
                'verbose_name_plural': '农业统计年鉴目录',
            },
        ),
    ]
