# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0022_yearbookscontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearbooks',
            options={'verbose_name': '农业统计年鉴详情', 'verbose_name_plural': '农业统计年鉴详情'},
        ),
        migrations.AlterModelTable(
            name='yearbooks',
            table='农业统计年鉴详情',
        ),
    ]
