# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0022_auto_20180111_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='NygjtpDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.CharField(blank=True, db_column='记录号', max_length=64, null=True, verbose_name='记录号')),
                ('image', models.CharField(blank=True, db_column='链接', max_length=200, null=True, verbose_name='链接')),
            ],
            options={
                'db_table': '农业古籍图片数据库',
                'verbose_name_plural': '农业古籍图片数据库',
                'verbose_name': '农业古籍图片数据库',
            },
        ),
    ]
