# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0023_auto_20180202_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbooks',
            name='category',
            field=models.CharField(db_column='目录', max_length=60, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='yearbooks',
            name='identify',
            field=models.CharField(db_column='编号', max_length=20, primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='yearbooks',
            name='year',
            field=models.ForeignKey(db_column='年鉴年份', on_delete=django.db.models.deletion.CASCADE, to='resource.YearBooksDes', verbose_name='年鉴年份'),
        ),
    ]
