# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0023_nygjtpdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nygjdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='nygjdb',
            name='reportid',
            field=models.CharField(db_column='记录号', max_length=64, primary_key=True, serialize=False, verbose_name='记录号'),
        ),
    ]
