# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0024_auto_20180112_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nygjtpdb',
            name='reportid',
            field=models.ForeignKey(blank=True, db_column='记录号', null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.NygjDb', verbose_name='记录号'),
        ),
    ]
