# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0024_auto_20180202_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriTechContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, db_column='顺序', null=True, verbose_name='顺序')),
                ('content', models.CharField(blank=True, db_column='目录', max_length=30, null=True, verbose_name='目录')),
                ('fieldtype', models.CharField(blank=True, db_column='字段类型', max_length=20, null=True, verbose_name='字段类型')),
                ('fieldlength', models.CharField(blank=True, db_column='字段长度', max_length=10, null=True, verbose_name='字段长度')),
            ],
            options={
                'verbose_name_plural': '农业科技数据目录',
                'verbose_name': '农业科技数据目录',
                'db_table': '农业科技数据目录',
            },
        ),
        migrations.CreateModel(
            name='AgriTechDes',
            fields=[
                ('selectid', models.CharField(blank=True, db_column='查询号码', max_length=40, null=True, verbose_name='查询号码')),
                ('id', models.CharField(blank=True, db_column='元数据标识符', max_length=40, null=True, verbose_name='元数据标识符')),
                ('title', models.CharField(db_column='数据集名称', max_length=60, primary_key=True, serialize=False, verbose_name='数据集名称')),
                ('english', models.CharField(blank=True, db_column='数据集英文名称', max_length=100, null=True, verbose_name='数据集英文名称')),
                ('language', models.CharField(blank=True, db_column='数据集语种', max_length=40, null=True, verbose_name='数据集语种\t')),
                ('endtime', models.CharField(blank=True, db_column='数据集完成日期', max_length=40, null=True, verbose_name='数据集完成日期')),
                ('category', models.CharField(blank=True, db_column='数据集分类', max_length=40, null=True, verbose_name='数据集分类\t')),
                ('keywords', models.CharField(blank=True, db_column='关键词', max_length=100, null=True, verbose_name='关键词')),
                ('abstract', models.CharField(blank=True, db_column='数据集摘要', max_length=200, null=True, verbose_name='数据集摘要')),
                ('resource', models.CharField(blank=True, db_column='数据来源', max_length=100, null=True, verbose_name='数据来源')),
                ('link', models.CharField(blank=True, db_column='在线链接地址', max_length=100, null=True, verbose_name='在线链接地址')),
                ('update', models.CharField(blank=True, db_column='维护和更新频率', max_length=40, null=True, verbose_name='维护和更新频率')),
                ('limit', models.CharField(blank=True, db_column='数据集使用局限性', max_length=40, null=True, verbose_name='数据集使用局限性')),
                ('safelimit', models.CharField(blank=True, db_column='数据集安全限制分级', max_length=40, null=True, verbose_name='数据集安全限制分级')),
                ('uselimit', models.CharField(blank=True, db_column='数据集使用限制', max_length=40, null=True, verbose_name='数据集使用限制')),
                ('accesslimit', models.CharField(blank=True, db_column='数据集访问限制', max_length=40, null=True, verbose_name='数据集访问限制')),
                ('unit', models.CharField(blank=True, db_column='负责单位', max_length=40, null=True, verbose_name='负责单位')),
                ('dutyer', models.CharField(blank=True, db_column='负责人', max_length=40, null=True, verbose_name='负责人')),
                ('duty', models.CharField(blank=True, db_column='职责', max_length=40, null=True, verbose_name='职责')),
                ('country', models.CharField(blank=True, db_column='国家', max_length=40, null=True, verbose_name='国家')),
                ('city', models.CharField(blank=True, db_column='城市', max_length=40, null=True, verbose_name='城市')),
                ('address', models.CharField(blank=True, db_column='地址', max_length=40, null=True, verbose_name='地址')),
                ('post', models.CharField(blank=True, db_column='邮政编码', max_length=40, null=True, verbose_name='邮政编码')),
                ('email', models.CharField(blank=True, db_column='电子邮件地址', max_length=40, null=True, verbose_name='电子邮件地址')),
                ('phone', models.CharField(blank=True, db_column='电话', max_length=40, null=True, verbose_name='电话')),
                ('fax', models.CharField(blank=True, db_column='传真', max_length=40, null=True, verbose_name='传真')),
            ],
            options={
                'verbose_name_plural': '农业科技数据概述',
                'verbose_name': '农业科技数据概述',
                'db_table': '农业科技数据概述',
            },
        ),
        migrations.AddField(
            model_name='agritechcontent',
            name='title',
            field=models.ForeignKey(blank=True, db_column='数据集名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.AgriTechDes', verbose_name='数据集名称'),
        ),
    ]
