# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0025_auto_20180202_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='agritechcontent',
            name='display',
            field=models.IntegerField(blank=True, db_column='是否显示', default=0, null=True, verbose_name='是否显示'),
        ),
    ]
