# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0025_auto_20180112_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nygjtpdb',
            name='image',
            field=models.ImageField(blank=True, db_column='链接', max_length=200, null=True, upload_to='', verbose_name='链接'),
        ),
    ]
