# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0026_auto_20180112_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='nygjtpdb',
            name='page',
            field=models.IntegerField(blank=True, db_column='页码', null=True, verbose_name='页码'),
        ),
    ]
