# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0026_agritechcontent_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gnnykyhzxmdb',
            options={'verbose_name': '国内农业科研项目数据库', 'verbose_name_plural': '国内农业科研项目数据库'},
        ),
        migrations.AddField(
            model_name='agritechcontent',
            name='english',
            field=models.IntegerField(blank=True, db_column='字段', default=0, null=True, verbose_name='字段'),
        ),
        migrations.AlterModelTable(
            name='gnnykyhzxmdb',
            table='国内农业科研项目数据库',
        ),
    ]
