# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0027_auto_20171124_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgwlrqzwdb',
            name='desc',
            field=models.TextField(blank=True, db_column='生物学特征及发生消长规律', null=True, verbose_name='生物学特征及发生消长规律'),
        ),
        migrations.AlterField(
            model_name='zgwlrqzwdb',
            name='id',
            field=models.IntegerField(db_column='编号', primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
