# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0027_nygjtpdb_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nygjtpdb',
            name='image',
            field=models.ImageField(blank=True, db_column='链接', null=True, upload_to='agridata/images', verbose_name='链接'),
        ),
    ]
