# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0027_auto_20180202_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agritechcontent',
            name='english',
            field=models.CharField(blank=True, db_column='字段', max_length=20, null=True, verbose_name='字段'),
        ),
    ]
