# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0028_auto_20180202_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyhjkjcgdb',
            old_name='catergory',
            new_name='category',
        ),
    ]
