# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0028_auto_20180112_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nygjtpdb',
            old_name='image',
            new_name='link',
        ),
    ]
