# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0029_auto_20180203_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytxdb',
            old_name='name',
            new_name='pzname',
        ),
    ]
