# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0029_auto_20180112_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgzynywhyctp',
            options={'verbose_name': '中国重要农业文化遗产图片', 'verbose_name_plural': '中国重要农业文化遗产图片'},
        ),
        migrations.RenameField(
            model_name='zgzynywhyctp',
            old_name='path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='nygjtpdb',
            name='link',
        ),
        migrations.AddField(
            model_name='nygjtpdb',
            name='image',
            field=models.ImageField(blank=True, db_column='链接', null=True, upload_to='agridata/images', verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='zgzynywhyctp',
            name='title',
            field=models.ForeignKey(blank=True, db_column='标题', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='resource.ZgzynywhYc', verbose_name='标题'),
        ),
        migrations.AlterModelTable(
            name='zgzynywhyctp',
            table='中国重要农业文化遗产图片',
        ),
    ]
