# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0030_auto_20180112_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='zggjhcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zggslschcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zghdzcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zghlzwhcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgjjzwbdbhdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgjjzwxjbhdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgjjzwzjbhdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zglszwbdbhdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zglszwxjbhdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zglszwzjbhdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgmhhcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgnthsdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgnttdzzdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgnytdkcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgpgtlhcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgsdhcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgstzcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgwlrqkcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgwlrqzwdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='zgyclschcdb',
            name='image',
            field=models.ImageField(blank=True, db_column='图片', null=True, upload_to='agridata/images', verbose_name='图片'),
        ),
    ]
