# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0030_auto_20180203_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nykjzcfgdb',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
