# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0030_auto_20171124_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZwyyzyzzDb',
            fields=[
                ('name', models.CharField(db_column='种质名称', max_length=40, primary_key=True, serialize=False, verbose_name='种质名称')),
                ('xiaolei', models.CharField(blank=True, db_column='种质小类', max_length=20, null=True, verbose_name='种质小类')),
                ('dalei', models.CharField(blank=True, db_column='种质大类', max_length=20, null=True, verbose_name='种质大类')),
                ('type', models.CharField(blank=True, db_column='种质类型', max_length=60, null=True, verbose_name='种质类型')),
                ('source', models.TextField(blank=True, db_column='种质来源', null=True, verbose_name='种质来源')),
                ('shape', models.TextField(blank=True, db_column='优异性状', null=True, verbose_name='优异性状')),
                ('values', models.TextField(blank=True, db_column='利用价值', null=True, verbose_name='利用价值')),
                ('evaluate_class', models.CharField(blank=True, db_column='评定等级', max_length=10, null=True, verbose_name='评定等级')),
                ('unit', models.CharField(blank=True, db_column='联系单位', max_length=30, null=True, verbose_name='联系单位')),
            ],
            options={
                'verbose_name_plural': '作物优异资源种质数据库',
                'db_table': '作物优异资源种质数据库',
                'managed': False,
                'verbose_name': '作物优异资源种质数据库',
            },
        ),
    ]
