# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0031_zwyyzyzzdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zwyyzyzzdb',
            options={'verbose_name': '作物优异资源种质数据库', 'verbose_name_plural': '作物优异资源种质数据库'},
        ),
    ]
