# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0031_auto_20180203_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nygjdb',
            old_name='datetimes',
            new_name='pubtime',
        ),
    ]
