# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0032_auto_20171124_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZwyyzyzzDb',
        ),
    ]
