# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0032_auto_20180203_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='agritechdes',
            name='index',
            field=models.IntegerField(blank=True, db_column='显示顺序', null=True, verbose_name='显示顺序'),
        ),
    ]
