# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0033_agritechdes_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GjnydbDes',
            fields=[
                ('title', models.CharField(db_column='数据集名称', max_length=60, primary_key=True, serialize=False, verbose_name='数据集名称')),
                ('index', models.IntegerField(db_column='显示顺序', default=0, verbose_name='显示顺序')),
                ('click_num', models.IntegerField(db_column='点击数', default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(db_column='收藏数', default=0, verbose_name='收藏数')),
                ('resource', models.CharField(blank=True, db_column='来源', max_length=60, null=True, verbose_name='来源')),
                ('down_num', models.CharField(blank=True, db_column='下载次数', max_length=20, null=True, verbose_name='下载次数')),
                ('pubtime', models.CharField(blank=True, db_column='发布时间', max_length=20, null=True, verbose_name='发布时间')),
                ('desc', models.CharField(blank=True, db_column='简介', max_length=200, null=True, verbose_name='简介')),
            ],
            options={
                'db_table': '国家农业数据集概述',
                'verbose_name': '国家农业数据集概述',
                'verbose_name_plural': '国家农业数据集概述',
            },
        ),
        migrations.AddField(
            model_name='agritechdes',
            name='click_num',
            field=models.IntegerField(db_column='点击数', default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='agritechdes',
            name='fav_num',
            field=models.IntegerField(db_column='收藏数', default=0, verbose_name='收藏数'),
        ),
    ]
