# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0034_auto_20180203_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gjnydbdes',
            name='click_num',
            field=models.IntegerField(blank=True, db_column='点击数', default=0, null=True, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='gjnydbdes',
            name='fav_num',
            field=models.IntegerField(blank=True, db_column='收藏数', default=0, null=True, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='gjnydbdes',
            name='index',
            field=models.IntegerField(blank=True, db_column='显示顺序', default=0, null=True, verbose_name='显示顺序'),
        ),
    ]
