# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0034_zwyyzyzzdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZgnyyhswDb_tupian',
            new_name='ZgnyyhswDb_image',
        ),
        migrations.RenameModel(
            old_name='Zgzynywhyc_tupian',
            new_name='Zgzynywhyc_image',
        ),
        migrations.AlterField(
            model_name='xzqhlist',
            name='city',
            field=models.CharField(blank=True, db_column='城市', max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='xzqhlist',
            name='county',
            field=models.CharField(blank=True, db_column='区县', max_length=20, null=True, verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='xzqhlist',
            name='province',
            field=models.CharField(blank=True, db_column='省份', max_length=20, null=True, verbose_name='省份'),
        ),
    ]
