# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0035_auto_20180203_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgnttdzzdb',
            options={'verbose_name': '中国农业天敌蜘蛛数据库', 'verbose_name_plural': '中国农业天敌蜘蛛数据库'},
        ),
        migrations.AlterModelTable(
            name='zgnttdzzdb',
            table='中国农业天敌蜘蛛数据库',
        ),
    ]
