# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0035_auto_20171124_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xzqhlist',
            name='alias',
            field=models.CharField(blank=True, db_column='别名', max_length=10, null=True, verbose_name='别名'),
        ),
    ]
