# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0036_auto_20171124_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agriindex',
            options={'managed': False, 'verbose_name': '农业统计指标', 'verbose_name_plural': '农业统计指标'},
        ),
        migrations.AlterModelOptions(
            name='gwyjzwzzzydb',
            options={'managed': False, 'verbose_name': '国外引进作物种质资源数据库', 'verbose_name_plural': '国外引进作物种质资源数据库'},
        ),
        migrations.AlterModelOptions(
            name='mytxdb',
            options={'managed': False, 'verbose_name': '农作物名、优、特新品种数据库', 'verbose_name_plural': '农作物名、优、特新品种数据库'},
        ),
        migrations.AlterModelOptions(
            name='ncpjgdb',
            options={'managed': False, 'verbose_name': '农产品价格行情数据库', 'verbose_name_plural': '农产品价格行情数据库'},
        ),
        migrations.AlterModelOptions(
            name='ncpjghqzdcode',
            options={'managed': False, 'verbose_name': '农产品价格行情字段编码', 'verbose_name_plural': '农产品价格行情字段编码'},
        ),
        migrations.AlterModelOptions(
            name='sdycpzjqpxdb',
            options={'managed': False, 'verbose_name': '水稻育成品种及其系谱数据库', 'verbose_name_plural': '水稻育成品种及其系谱数据库'},
        ),
        migrations.AlterModelOptions(
            name='sdzzzzhxzzdb',
            options={'managed': False, 'verbose_name': '水稻种质资源核心种质数据库', 'verbose_name_plural': '水稻种质资源核心种质数据库'},
        ),
        migrations.AlterModelOptions(
            name='xdnysfq',
            options={'managed': False, 'verbose_name': '现代农业示范区', 'verbose_name_plural': '现代农业示范区'},
        ),
        migrations.AlterModelOptions(
            name='xmxcpzjqxpdb',
            options={'managed': False, 'verbose_name': '小麦育成品种及其系谱数据库', 'verbose_name_plural': '小麦育成品种及其系谱数据库'},
        ),
        migrations.AlterModelOptions(
            name='xmxpdb',
            options={'managed': False, 'verbose_name': '小麦系谱数据库', 'verbose_name_plural': '小麦系谱数据库'},
        ),
        migrations.AlterModelOptions(
            name='xmzzzzhxzzdb',
            options={'managed': False, 'verbose_name': '小麦种质资源核心种质数据库', 'verbose_name_plural': '小麦种质资源核心种质数据库'},
        ),
        migrations.AlterModelOptions(
            name='xzqhlist',
            options={'managed': False, 'verbose_name': '行政区划清单', 'verbose_name_plural': '行政区划清单'},
        ),
        migrations.AlterModelOptions(
            name='ymxpzbhdb',
            options={'managed': False, 'verbose_name': '玉米新品种保护数据库', 'verbose_name_plural': '玉米新品种保护数据库'},
        ),
        migrations.AlterModelOptions(
            name='ymzzzzhxzzdb',
            options={'managed': False, 'verbose_name': '玉米种质资源核心种质数据库', 'verbose_name_plural': '玉米种质资源核心种质数据库'},
        ),
        migrations.AlterModelOptions(
            name='zggjhcdb',
            options={'managed': False, 'verbose_name': '中国柑桔害虫数据库', 'verbose_name_plural': '中国柑桔害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zggslschcdb',
            options={'managed': False, 'verbose_name': '中国果菜类蔬菜害虫数据库', 'verbose_name_plural': '中国果菜类蔬菜害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zghdzcdb',
            options={'managed': False, 'verbose_name': '中国旱地杂草数据库', 'verbose_name_plural': '中国旱地杂草数据库'},
        ),
        migrations.AlterModelOptions(
            name='zghlzwhcdb',
            options={'managed': False, 'verbose_name': '中国旱粮作物害虫数据库', 'verbose_name_plural': '中国旱粮作物害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgjjzwbdbhdb',
            options={'managed': False, 'verbose_name': '中国经济作物病毒病害数据库', 'verbose_name_plural': '中国经济作物病毒病害数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgjjzwxjbhdb',
            options={'managed': False, 'verbose_name': '中国经济作物细菌病害数据库', 'verbose_name_plural': '中国经济作物细菌病害数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgjjzwzjbhdb',
            options={'managed': False, 'verbose_name': '中国经济作物真菌病害数据库', 'verbose_name_plural': '中国经济作物真菌病害数据库'},
        ),
        migrations.AlterModelOptions(
            name='zglszwbdbhdb',
            options={'managed': False, 'verbose_name': '中国粮食作物病毒病害数据库', 'verbose_name_plural': '中国粮食作物病毒病害数据库'},
        ),
        migrations.AlterModelOptions(
            name='zglszwxjbhdb',
            options={'managed': False, 'verbose_name': '中国粮食作物细菌病害数据库', 'verbose_name_plural': '中国粮食作物细菌病害数据库'},
        ),
        migrations.AlterModelOptions(
            name='zglszwzjbhdb',
            options={'managed': False, 'verbose_name': '中国粮食作物真菌病害数据库', 'verbose_name_plural': '中国粮食作物真菌病害数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgmhhcdb',
            options={'managed': False, 'verbose_name': '中国棉花害虫数据库', 'verbose_name_plural': '中国棉花害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgnthsdb',
            options={'managed': False, 'verbose_name': '中国农田害鼠数据库', 'verbose_name_plural': '中国农田害鼠数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgnttdzzdb',
            options={'managed': False, 'verbose_name': '中国农田天敌蜘蛛数据库', 'verbose_name_plural': '中国农田天敌蜘蛛数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgnytdkcdb',
            options={'managed': False, 'verbose_name': '中国农业天敌昆虫数据库', 'verbose_name_plural': '中国农业天敌昆虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgnyyhswdb_image',
            options={'managed': False, 'verbose_name': '中国农业有害生物数据库_图片', 'verbose_name_plural': '中国农业有害生物数据库_图片'},
        ),
        migrations.AlterModelOptions(
            name='zgpgtlhcdb',
            options={'managed': False, 'verbose_name': '中国苹果、桃、梨害虫数据库', 'verbose_name_plural': '中国苹果、桃、梨害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgsdhcdb',
            options={'managed': False, 'verbose_name': '中国水稻害虫数据库', 'verbose_name_plural': '中国水稻害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgstzcdb',
            options={'managed': False, 'verbose_name': '中国水田杂草数据库', 'verbose_name_plural': '中国水田杂草数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgtsncp',
            options={'managed': False, 'verbose_name': '中国特色农产品', 'verbose_name_plural': '中国特色农产品'},
        ),
        migrations.AlterModelOptions(
            name='zgwlrqkcdb',
            options={'managed': False, 'verbose_name': '中国外来入侵昆虫数据库', 'verbose_name_plural': '中国外来入侵昆虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgwlrqwswdb',
            options={'managed': False, 'verbose_name': '中国外来入侵微生物数据库', 'verbose_name_plural': '中国外来入侵微生物数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgwlrqzwdb',
            options={'managed': False, 'verbose_name': '中国外来入侵植物数据库', 'verbose_name_plural': '中国外来入侵植物数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgyclschcdb',
            options={'managed': False, 'verbose_name': '中国叶菜类蔬菜害虫数据库', 'verbose_name_plural': '中国叶菜类蔬菜害虫数据库'},
        ),
        migrations.AlterModelOptions(
            name='zgzynywhyc',
            options={'managed': False, 'verbose_name': '中国重要农业文化遗产', 'verbose_name_plural': '中国重要农业文化遗产'},
        ),
        migrations.AlterModelOptions(
            name='zgzynywhyc_image',
            options={'managed': False, 'verbose_name': '中国重要农业文化遗产_图片', 'verbose_name_plural': '中国重要农业文化遗产_图片'},
        ),
        migrations.AlterModelOptions(
            name='zwwzfbdb',
            options={'managed': False, 'verbose_name': '作物物种分布数据库', 'verbose_name_plural': '作物物种分布数据库'},
        ),
        migrations.AlterModelOptions(
            name='zwyyzyzzdb',
            options={'managed': False, 'verbose_name': '作物优异资源种质数据库', 'verbose_name_plural': '作物优异资源种质数据库'},
        ),
    ]
