# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0036_auto_20180203_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gjnydbdes',
            name='resource',
            field=models.CharField(blank=True, db_column='来源', max_length=100, null=True, verbose_name='来源'),
        ),
    ]
