# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0037_auto_20180203_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youdamai',
            options={'verbose_name': '作物优异资源综合评价数据库_大麦', 'verbose_name_plural': '作物优异资源综合评价数据库_大麦'},
        ),
        migrations.AlterModelOptions(
            name='youyumi',
            options={'verbose_name': '作物优异资源综合评价数据库_玉米', 'verbose_name_plural': '作物优异资源综合评价数据库_玉米'},
        ),
        migrations.AlterModelTable(
            name='youdamai',
            table='作物优异资源综合评价数据库_大麦',
        ),
        migrations.AlterModelTable(
            name='youyumi',
            table='作物优异资源综合评价数据库_玉米',
        ),
    ]
