# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0038_auto_20180203_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgnthsdb',
            options={'verbose_name': '中国农业害鼠数据库', 'verbose_name_plural': '中国农业害鼠数据库'},
        ),
        migrations.AlterModelTable(
            name='zgnthsdb',
            table='中国农业害鼠数据库',
        ),
    ]
