# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0039_auto_20180203_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zwyyzyzzdb',
            options={'verbose_name': '作物优异种质数据库', 'verbose_name_plural': '作物优异种质数据库'},
        ),
        migrations.AlterModelTable(
            name='zwyyzyzzdb',
            table='作物优异种质数据库',
        ),
    ]
