# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0040_auto_20180203_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwyjzwzzzydb',
            options={'verbose_name': '国外引进作物资源数据库', 'verbose_name_plural': '国外引进作物资源数据库'},
        ),
        migrations.AlterModelTable(
            name='gwyjzwzzzydb',
            table='国外引进作物资源数据库',
        ),
    ]
