# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0041_auto_20180203_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdzzzzhxzzdb',
            options={'verbose_name': '水稻作物核心种质数据库', 'verbose_name_plural': '水稻作物核心种质数据库'},
        ),
        migrations.AlterModelOptions(
            name='xmzzzzhxzzdb',
            options={'verbose_name': '小麦作物核心种质数据库', 'verbose_name_plural': '小麦作物核心种质数据库'},
        ),
        migrations.AlterModelOptions(
            name='ymzzzzhxzzdb',
            options={'verbose_name': '玉米作物核心种质数据库', 'verbose_name_plural': '玉米作物核心种质数据库'},
        ),
        migrations.AlterModelTable(
            name='sdzzzzhxzzdb',
            table='水稻作物核心种质数据库',
        ),
        migrations.AlterModelTable(
            name='xmzzzzhxzzdb',
            table='小麦作物核心种质数据库',
        ),
        migrations.AlterModelTable(
            name='ymzzzzhxzzdb',
            table='玉米作物核心种质数据库',
        ),
    ]
