# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0042_auto_20180203_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='gjnydbdes',
            name='category',
            field=models.CharField(blank=True, db_column='类别', max_length=10, null=True, verbose_name='类别'),
        ),
    ]
