# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0044_auto_20180203_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youdamai',
            options={'verbose_name': '大麦作物优异资源综合评价数据库', 'verbose_name_plural': '大麦作物优异资源综合评价数据库'},
        ),
        migrations.AlterModelOptions(
            name='youyumi',
            options={'verbose_name': '玉米作物优异资源综合评价数据库', 'verbose_name_plural': '玉米作物优异资源综合评价数据库'},
        ),
        migrations.AlterModelTable(
            name='youdamai',
            table='大麦作物优异资源综合评价数据库',
        ),
        migrations.AlterModelTable(
            name='youyumi',
            table='玉米作物优异资源综合评价数据库',
        ),
    ]
