# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20171208_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='chart',
            field=models.ForeignKey(blank=True, db_column='图片', null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Chart', verbose_name='图片'),
        ),
    ]
