# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_chartcomments_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(default='', verbose_name='消息内容'),
        ),
    ]
